### ISSUE TITLE
Executable Launch Results in Black Screen

### ISSUE THREAD

**Issue by dorensbach** [zaps166/NFSIISE#120]
Hi, I would like to report an issue I'm experiencing when trying to run the wrapper for your project. After cloning the repository and compiling the source code without encountering any errors, the executable is generated, but upon execution, the application opens a black screen and does not proceed further.

```
ls -gh
total 1,1M
-rw-r--r--  1 users  266 jul 29 13:57 clean_config.bat
-rwxr-xr-x  1 users 1,2K jul 29 13:57 convert_to_lowercase
drwxr-xr-x  3 users 4,0K mar 26  2006 fedata
drwxr-xr-x 12 users 4,0K jul 29 13:03 gamedata
-rw-r--r--  1 users  696 jul 29 13:57 install.win
-rwxr-xr-x  1 users 769K jul 29 14:09 nfs2se
-rw-r--r--  1 users 4,3K jul 29 13:57 nfs2se.conf.template
-rw-r--r--  1 users  238 jul 29 13:57 nfs2se.desktop
-rw-r--r--  1 users  370 jul 29 13:57 nfs2se.png
-rw-r--r--  1 users  163 jul 29 13:57 open_config.bat
-rw-r--r--  1 users  38K jul 29 13:57 text.eng
-rw-r--r--  1 users  38K jul 29 13:57 text.fre
-rw-r--r--  1 users  39K jul 29 13:57 text.ger
-rw-r--r--  1 users  38K jul 29 13:57 text.ita
-rw-r--r--  1 users  39K jul 29 13:57 text.spa
-rw-r--r--  1 users  38K jul 29 13:57 text.swe

./nfs2se 
Need For Speed II SE
Wrapper v1.4.0
Game    v1.1.5
OpenGL  2
```

**Comment by zaps166** [comment]
Hi, do you have sound?
Do you have 32-bit opengl drivers?
Do you have all NFSIISE files lower case?

**Comment by dorensbach** [comment]
> Hi, do you have sound?

On the PC, yes, but the game didn't load any sound.
> Do you have 32-bit opengl drivers?

In principle, yes, but I'm not sure. I'm sorry.
```
# ldconfig -p | grep libGL.so
libGL.so.1 (libc6,x86-64) => /usr/lib64/libGL.so.1
libGL.so.1 (libc6) => /usr/lib/libGL.so.1
libGL.so (libc6,x86-64) => /usr/lib64/libGL.so
libGL.so (libc6) => /usr/lib/libGL.so

```
> Do you have all NFSIISE files lower case?

Yes, with script `convert_to_lowercase`

**Comment by zaps166** [comment]
I don't know, you can always check binaries from here: https://github.com/zaps166/NFSIISE/releases

Also Windows binaries (works with Wine).

**Comment by dorensbach** [comment]
With Wine the same black screen appears.

**Comment by zaps166** [comment]
What's you GPU? What's your distribution?

**Comment by dorensbach** [comment]
GPU: NVIDIA GeForce GTX 1050
OS: Slackware 15.0 x86_64 (post 15.0 -current) x86_64

**Comment by zaps166** [comment]
Last time I used Slackware about 20y ago...

Do you have any other 32-bit game (can be on Steam) to test?

Could you try to run using gdb and check what's going on?

**Comment by dorensbach** [comment]
> Last time I used Slackware about 20y ago...

lol
> Do you have any other 32-bit game (can be on Steam) to test?  

I play some old ones, which I imagine are 32-bit, like Battlefield 1942, Rune and Unreal Tornament.
I manage them all through Heroic Launcher
> Could you try to run using gdb and check what's going on?  

```
(gdb) run
Starting program: /home/melkor/applications/games/need-for-speed-ii-se/nfs2se 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Need For Speed II SE
Wrapper v1.4.0
Game    v1.1.5
OpenGL  2
[New Thread 0xf7679b40 (LWP 5823)]
[New Thread 0xf6dd8b40 (LWP 5824)]
[New Thread 0xe5bfeb40 (LWP 5825)]
[New Thread 0xddc87b40 (LWP 5826)]
[New Thread 0xdd2ffb40 (LWP 5827)]
[New Thread 0xdc8ffb40 (LWP 5828)]
[New Thread 0xcbeffb40 (LWP 5829)]
[New Thread 0xcb6feb40 (LWP 5830)]
[New Thread 0xcaaffb40 (LWP 5831)]
[New Thread 0xca2feb40 (LWP 5832)]
[Thread 0xcaaffb40 (LWP 5831) exited]
[New Thread 0xcaaffb40 (LWP 5833)]
[Thread 0xdd2ffb40 (LWP 5827) exited]
[Thread 0xcb6feb40 (LWP 5830) exited]
[Thread 0xcaaffb40 (LWP 5833) exited]
[Thread 0xca2feb40 (LWP 5832) exited]
[Thread 0xcbeffb40 (LWP 5829) exited]
[Thread 0xdc8ffb40 (LWP 5828) exited]
[Thread 0xe5bfeb40 (LWP 5825) exited]
[Thread 0xf6dd8b40 (LWP 5824) exited]
[Thread 0xf7679b40 (LWP 5823) exited]
[Thread 0xf7c35a80 (LWP 5820) exited]
[Thread 0xddc87b40 (LWP 5826) exited]
[New process 5820]
[Inferior 1 (process 5820) exited normally]
(gdb) 
```

**Comment by zaps166** [comment]
So it starts and closes? I don't have any idea, it just works on my OS.
Last thing - check if it shows any audio output in e.g. `pavucontrol` - maybe it stucks there somehow?

**Comment by dorensbach** [comment]
Sorry. It doesn't close by itself.
I closed it.

Here's the complete output:

```
gdb nfs2se
GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nfs2se...
(No debugging symbols found in nfs2se)
(gdb) run
Starting program: /home/melkor/applications/games/need-for-speed-ii-se/nfs2se 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Need For Speed II SE
Wrapper v1.4.0
Game    v1.1.5
OpenGL  2
[New Thread 0xf7679b40 (LWP 8169)]
[New Thread 0xf6dd8b40 (LWP 8170)]
[New Thread 0xe5bfeb40 (LWP 8171)]
[New Thread 0xddc87b40 (LWP 8172)]
[New Thread 0xdd2ffb40 (LWP 8173)]
[New Thread 0xdc8ffb40 (LWP 8174)]
[New Thread 0xcbeffb40 (LWP 8177)]
[New Thread 0xcb6feb40 (LWP 8178)]
[New Thread 0xcaaffb40 (LWP 8179)]
[New Thread 0xca2feb40 (LWP 8180)]
[Thread 0xcaaffb40 (LWP 8179) exited]
[New Thread 0xcaaffb40 (LWP 8181)]
```

**Comment by dorensbach** [comment]
![image](https://github.com/user-attachments/assets/72de73d0-ff7d-4f7e-ac41-fc99e6b38f04)

**Comment by zaps166** [comment]
What if you kill the audio stream?
What if you break on gdb and write `bt`?

**Comment by dorensbach** [comment]
When I end playback in pavucontrol, nothing happens.

**Comment by dorensbach** [comment]
Could this be relevant?
```
Need For Speed II SE
Wrapper v1.4.0
Game    v1.1.5
OpenGL  2
[New Thread 0xf7679b40 (LWP 2260)]
[New Thread 0xf6dd8b40 (LWP 2261)]
[New Thread 0xe5bfeb40 (LWP 2262)]
[New Thread 0xddc87b40 (LWP 2263)]
[New Thread 0xdd2ffb40 (LWP 2264)]
[New Thread 0xdc8ffb40 (LWP 2265)]
[New Thread 0xcbeffb40 (LWP 2266)]
[New Thread 0xcb6feb40 (LWP 2267)]
[New Thread 0xcaaffb40 (LWP 2268)]
[New Thread 0xca2feb40 (LWP 2269)]
[Thread 0xcaaffb40 (LWP 2268) exited]
[New Thread 0xcaaffb40 (LWP 2271)]
^C
Thread 1 "nfs2se" received signal SIGINT, Interrupt.
0xf7db45c6 in ?? () from /usr/lib/libSDL2-2.0.so.0
(gdb) 
```

**Comment by dorensbach** [comment]
```
Need For Speed II SE
Wrapper v1.4.0
Game    v1.1.5
OpenGL  2
[New Thread 0xf7679b40 (LWP 2260)]
[New Thread 0xf6dd8b40 (LWP 2261)]
[New Thread 0xe5bfeb40 (LWP 2262)]
[New Thread 0xddc87b40 (LWP 2263)]
[New Thread 0xdd2ffb40 (LWP 2264)]
[New Thread 0xdc8ffb40 (LWP 2265)]
[New Thread 0xcbeffb40 (LWP 2266)]
[New Thread 0xcb6feb40 (LWP 2267)]
[New Thread 0xcaaffb40 (LWP 2268)]
[New Thread 0xca2feb40 (LWP 2269)]
[Thread 0xcaaffb40 (LWP 2268) exited]
[New Thread 0xcaaffb40 (LWP 2271)]
^C
Thread 1 "nfs2se" received signal SIGINT, Interrupt.
0xf7db45c6 in ?? () from /usr/lib/libSDL2-2.0.so.0
(gdb) bt
#0  0xf7db45c6 in ?? () from /usr/lib/libSDL2-2.0.so.0
#1  0xf7dd70b5 in SDL_UnlockMutex () from /usr/lib/libSDL2-2.0.so.0
#2  0x080ee3fb in ?? ()
#3  0x080ca250 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 

```

**Comment by zaps166** [comment]
Stuck on unlock mutex? Hmm. Hard to say why. If you have windows, try there. If it will not run there, it's dara issue. Where did you get game data?

**Comment by dorensbach** [comment]
I get from [oldgamesdownload](https://oldgamesdownload.com/need-for-speed-ii-special-edition-gl9/)

**Comment by dorensbach** [comment]
I've just tried with data from another source.
Same problem.

**Comment by zaps166** [comment]
No idea, sorry. I never had this problem. Try Windows?

**Comment by zaps166** [comment]
> No idea, sorry. I never had this problem. Try Windows?

Forget about this. I realized I can download game data from your link. Doesn't work - try to find another game data, best NFSIISE ISO image.

**Comment by zaps166** [comment]
My data has 535.9 MiB, yours only 126.3 MiB - missing files for sure.

**Comment by HalanoSiblee** [comment]
same problem I've ripped version why doesn't the engine just skip the movie part ?

edit :

---

I downloaded the full game and it works thanks.
